In [1]:
import numpy as np
import pandas as pd

In [2]:
companies = pd.read_csv('CompanyInfo_2000-2021_WithL_Final.csv')
companies

,gvkey,datadate,fyear,indfmt,consol,popsrc,datafmt,tic,conm,curcd,costat,add1,addzip,city,fyrc,cyear,longitude,latitude
0,1004,20000531,1999,INDL,C,D,STD,AIR,AAR CORP,USD,A,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,5,2000,10.612850,56.304543
1,1004,20010531,2000,INDL,C,D,STD,AIR,AAR CORP,USD,A,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,5,2001,10.612850,56.304543
2,1004,20020531,2001,INDL,C,D,STD,AIR,AAR CORP,USD,A,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,5,2002,10.612850,56.304543
3,1004,20030531,2002,INDL,C,D,STD,AIR,AAR CORP,USD,A,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,5,2003,10.612850,56.304543
4,1004,20040531,2003,INDL,C,D,STD,AIR,AAR CORP,USD,A,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,5,2004,10.612850,56.304543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225754,345980,20151231,2015,INDL,C,D,STD,WISH,CONTEXTLOGIC INC,USD,A,"One Sansome Street, 40th Floor",94104-4418,San Francisco,12,2015,-122.401955,37.797070
225755,345980,20161231,2016,INDL,C,D,STD,WISH,CONTEXTLOGIC INC,USD,A,"One Sansome Street, 40th Floor",94104-4418,San Francisco,12,2016,-122.401955,37.797070
225756,345980,20171231,2017,INDL,C,D,STD,WISH,CONTEXTLOGIC INC,USD,A,"One Sansome Street, 40th Floor",94104-4418,San Francisco,12,2017,-122.401955,37.797070
225757,345980,20181231,2018,INDL,C,D,STD,WISH,CONTEXTLOGIC INC,USD,A,"One Sansome Street, 40th Floor",94104-4418,San Francisco,12,2018,-122.401955,37.797070
225758,345980,20191231,2019,INDL,C,D,STD,WISH,CONTEXTLOGIC INC,USD,A,"One Sansome Street, 40th Floor",94104-4418,San Francisco,12,2019,-122.401955,37.797070

In [3]:
companies = companies.drop(columns = ['gvkey', 'fyear','indfmt','consol','popsrc','datafmt','curcd',
                                     'costat','fyrc','datadate'])
companies

,tic,conm,add1,addzip,city,cyear,longitude,latitude
0,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2000,10.612850,56.304543
1,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2001,10.612850,56.304543
2,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2002,10.612850,56.304543
3,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2003,10.612850,56.304543
4,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2004,10.612850,56.304543
...,...,...,...,...,...,...,...,...
225754,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2015,-122.401955,37.797070
225755,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2016,-122.401955,37.797070
225756,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2017,-122.401955,37.797070
225757,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2018,-122.401955,37.797070
225758,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2019,-122.401955,37.797070

In [4]:
companies['longitude'] = companies['longitude'].round(2)
companies['latitude'] = companies['latitude'].round(2)
companies

,tic,conm,add1,addzip,city,cyear,longitude,latitude
0,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2000,10.61,56.3
1,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2001,10.61,56.3
2,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2002,10.61,56.3
3,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2003,10.61,56.3
4,AIR,AAR CORP,"One AAR Place, 1100 North Wood Dale Road",60191,Wood Dale,2004,10.61,56.3
...,...,...,...,...,...,...,...,...
225754,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2015,-122.40,37.8
225755,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2016,-122.40,37.8
225756,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2017,-122.40,37.8
225757,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2018,-122.40,37.8
225758,WISH,CONTEXTLOGIC INC,"One Sansome Street, 40th Floor",94104-4418,San Francisco,2019,-122.40,37.8

In [8]:
years = companies.cyear.unique().tolist()

In [7]:
for yr in years:
    yr_df = pd.DataFrame(data= companies[companies.cyear == yr])
    yr_df.to_csv('companies_%s.csv'%yr)

In [9]:
PM2000 = pd.read_csv('PM25_NA_2000.csv')
PM2000

,Unnamed: 0,-137.99,-137.98,-137.97,-137.96,-137.95,-137.94,-137.93,-137.92,-137.91,...,-45.09,-45.08,-45.07,-45.06,-45.05,-45.04,-45.03,-45.02,-45.01,-45.0
0,22.50,1.3,1.3,1.3,1.3,1.3,1.2,1.2,1.2,1.3,...,1.4,1.4,1.4,1.3,1.3,1.4,1.4,1.4,1.4,1.4
1,22.51,1.3,1.3,1.3,1.3,1.2,1.2,1.2,1.2,1.2,...,1.4,1.4,1.4,1.4,1.3,1.4,1.4,1.4,1.4,1.4
2,22.52,1.3,1.3,1.3,1.3,1.3,1.3,1.2,1.3,1.3,...,1.3,1.4,1.4,1.4,1.4,1.4,1.4,1.4,1.4,1.4
3,22.53,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3,...,1.4,1.4,1.4,1.4,1.4,1.4,1.4,1.4,1.4,1.4
4,22.54,1.4,1.4,1.4,1.4,1.3,1.3,1.3,1.3,1.3,...,1.4,1.4,1.4,1.4,1.4,1.4,1.4,1.4,1.4,1.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4545,67.95,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,...,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9
4546,67.96,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,...,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9
4547,67.97,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,...,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9
4548,67.98,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,...,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9
4549,67.99,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,...,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9,-999.9

In [ ]:
for xi in range(0,9300):
    x=round(xi*0.01-137.99,2)
        x_list.append(x)

    for yi in range(0,4550):
        y=round(yi*0.01+22.50,2)

In [10]:
lang= PM2000.columns.tolist()
lang= lang[1:]
lati= PM2000['Unnamed: 0'].tolist()

In [16]:
t1 = float(companies.iloc[225757,6])
t2 = companies.iloc[225757,7]
print(t1,t2)

-122.4 37.8

In [45]:
lang

['-137.99',
 '-137.98',
 '-137.97',
 '-137.96',
 '-137.95',
 '-137.94',
 '-137.93',
 '-137.92',
 '-137.91',
 '-137.9',
 '-137.89',
 '-137.88',
 '-137.87',
 '-137.86',
 '-137.85',
 '-137.84',
 '-137.83',
 '-137.82',
 '-137.81',
 '-137.8',
 '-137.79',
 '-137.78',
 '-137.77',
 '-137.76',
 '-137.75',
 '-137.74',
 '-137.73',
 '-137.72',
 '-137.71',
 '-137.7',
 '-137.69',
 '-137.68',
 '-137.67',
 '-137.66',
 '-137.65',
 '-137.64',
 '-137.63',
 '-137.62',
 '-137.61',
 '-137.6',
 '-137.59',
 '-137.58',
 '-137.57',
 '-137.56',
 '-137.55',
 '-137.54',
 '-137.53',
 '-137.52',
 '-137.51',
 '-137.5',
 '-137.49',
 '-137.48',
 '-137.47',
 '-137.46',
 '-137.45',
 '-137.44',
 '-137.43',
 '-137.42',
 '-137.41',
 '-137.4',
 '-137.39',
 '-137.38',
 '-137.37',
 '-137.36',
 '-137.35',
 '-137.34',
 '-137.33',
 '-137.32',
 '-137.31',
 '-137.3',
 '-137.29',
 '-137.28',
 '-137.27',
 '-137.26',
 '-137.25',
 '-137.24',
 '-137.23',
 '-137.22',
 '-137.21',
 '-137.2',
 '-137.19',
 '-137.18',
 '-137.17',
 '-137.16',
 '-137.15',
 '-137.14',
 '-137.13',
 '-137.12',
 '-137.11',
 '-137.1',
 '-137.09',
 '-137.08',
 '-137.07',
 '-137.06',
 '-137.05',
 '-137.04',
 '-137.03',
 '-137.02',
 '-137.01',
 '-137.0',
 '-136.99',
 '-136.98',
 '-136.97',
 '-136.96',
 '-136.95',
 '-136.94',
 '-136.93',
 '-136.92',
 '-136.91',
 '-136.9',
 '-136.89',
 '-136.88',
 '-136.87',
 '-136.86',
 '-136.85',
 '-136.84',
 '-136.83',
 '-136.82',
 '-136.81',
 '-136.8',
 '-136.79',
 '-136.78',
 '-136.77',
 '-136.76',
 '-136.75',
 '-136.74',
 '-136.73',
 '-136.72',
 '-136.71',
 '-136.7',
 '-136.69',
 '-136.68',
 '-136.67',
 '-136.66',
 '-136.65',
 '-136.64',
 '-136.63',
 '-136.62',
 '-136.61',
 '-136.6',
 '-136.59',
 '-136.58',
 '-136.57',
 '-136.56',
 '-136.55',
 '-136.54',
 '-136.53',
 '-136.52',
 '-136.51',
 '-136.5',
 '-136.49',
 '-136.48',
 '-136.47',
 '-136.46',
 '-136.45',
 '-136.44',
 '-136.43',
 '-136.42',
 '-136.41',
 '-136.4',
 '-136.39',
 '-136.38',
 '-136.37',
 '-136.36',
 '-136.35',
 '-136.34',
 '-136.33',
 '-136.32',
 '-136.31',
 '-136.3',
 '-136.29',
 '-136.28',
 '-136.27',
 '-136.26',
 '-136.25',
 '-136.24',
 '-136.23',
 '-136.22',
 '-136.21',
 '-136.2',
 '-136.19',
 '-136.18',
 '-136.17',
 '-136.16',
 '-136.15',
 '-136.14',
 '-136.13',
 '-136.12',
 '-136.11',
 '-136.1',
 '-136.09',
 '-136.08',
 '-136.07',
 '-136.06',
 '-136.05',
 '-136.04',
 '-136.03',
 '-136.02',
 '-136.01',
 '-136.0',
 '-135.99',
 '-135.98',
 '-135.97',
 '-135.96',
 '-135.95',
 '-135.94',
 '-135.93',
 '-135.92',
 '-135.91',
 '-135.9',
 '-135.89',
 '-135.88',
 '-135.87',
 '-135.86',
 '-135.85',
 '-135.84',
 '-135.83',
 '-135.82',
 '-135.81',
 '-135.8',
 '-135.79',
 '-135.78',
 '-135.77',
 '-135.76',
 '-135.75',
 '-135.74',
 '-135.73',
 '-135.72',
 '-135.71',
 '-135.7',
 '-135.69',
 '-135.68',
 '-135.67',
 '-135.66',
 '-135.65',
 '-135.64',
 '-135.63',
 '-135.62',
 '-135.61',
 '-135.6',
 '-135.59',
 '-135.58',
 '-135.57',
 '-135.56',
 '-135.55',
 '-135.54',
 '-135.53',
 '-135.52',
 '-135.51',
 '-135.5',
 '-135.49',
 '-135.48',
 '-135.47',
 '-135.46',
 '-135.45',
 '-135.44',
 '-135.43',
 '-135.42',
 '-135.41',
 '-135.4',
 '-135.39',
 '-135.38',
 '-135.37',
 '-135.36',
 '-135.35',
 '-135.34',
 '-135.33',
 '-135.32',
 '-135.31',
 '-135.3',
 '-135.29',
 '-135.28',
 '-135.27',
 '-135.26',
 '-135.25',
 '-135.24',
 '-135.23',
 '-135.22',
 '-135.21',
 '-135.2',
 '-135.19',
 '-135.18',
 '-135.17',
 '-135.16',
 '-135.15',
 '-135.14',
 '-135.13',
 '-135.12',
 '-135.11',
 '-135.1',
 '-135.09',
 '-135.08',
 '-135.07',
 '-135.06',
 '-135.05',
 '-135.04',
 '-135.03',
 '-135.02',
 '-135.01',
 '-135.0',
 '-134.99',
 '-134.98',
 '-134.97',
 '-134.96',
 '-134.95',
 '-134.94',
 '-134.93',
 '-134.92',
 '-134.91',
 '-134.9',
 '-134.89',
 '-134.88',
 '-134.87',
 '-134.86',
 '-134.85',
 '-134.84',
 '-134.83',
 '-134.82',
 '-134.81',
 '-134.8',
 '-134.79',
 '-134.78',
 '-134.77',
 '-134.76',
 '-134.75',
 '-134.74',
 '-134.73',
 '-134.72',
 '-134.71',
 '-134.7',
 '-134.69',
 '-134.68',
 '-134.67',
 '-134.66',
 '-134.65',
 '-134.64',
 '-134.63',
 '-134.62',
 '-134.61',
 '-134.6',
 '-134.59',
 '-134.58',
 '-134.57',
 '-134.56',
 '-134.55',
 '-134.54',
 '-134.53',
 '-134.52',
 '-134.51',
 '-134.5',
 '-134.49',
 '-134.48',
 '-134.47',
 '-134.46',
 '-134.45',
 '-134.44',
 '-134.43',
 '-134.42',
 '-134.41',
 '-134.4',
 '-134.39',
 '-134.38',
 '-134.37',
 '-134.36',
 '-134.35',
 '-134.34',
 '-134.33',
 '-134.32',
 '-134.31',
 '-134.3',
 '-134.29',
 '-134.28',
 '-134.27',
 '-134.26',
 '-134.25',
 '-134.24',
 '-134.23',
 '-134.22',
 '-134.21',
 '-134.2',
 '-134.19',
 '-134.18',
 '-134.17',
 '-134.16',
 '-134.15',
 '-134.14',
 '-134.13',
 '-134.12',
 '-134.11',
 '-134.1',
 '-134.09',
 '-134.08',
 '-134.07',
 '-134.06',
 '-134.05',
 '-134.04',
 '-134.03',
 '-134.02',
 '-134.01',
 '-134.0',
 '-133.99',
 '-133.98',
 '-133.97',
 '-133.96',
 '-133.95',
 '-133.94',
 '-133.93',
 '-133.92',
 '-133.91',
 '-133.9',
 '-133.89',
 '-133.88',
 '-133.87',
 '-133.86',
 '-133.85',
 '-133.84',
 '-133.83',
 '-133.82',
 '-133.81',
 '-133.8',
 '-133.79',
 '-133.78',
 '-133.77',
 '-133.76',
 '-133.75',
 '-133.74',
 '-133.73',
 '-133.72',
 '-133.71',
 '-133.7',
 '-133.69',
 '-133.68',
 '-133.67',
 '-133.66',
 '-133.65',
 '-133.64',
 '-133.63',
 '-133.62',
 '-133.61',
 '-133.6',
 '-133.59',
 '-133.58',
 '-133.57',
 '-133.56',
 '-133.55',
 '-133.54',
 '-133.53',
 '-133.52',
 '-133.51',
 '-133.5',
 '-133.49',
 '-133.48',
 '-133.47',
 '-133.46',
 '-133.45',
 '-133.44',
 '-133.43',
 '-133.42',
 '-133.41',
 '-133.4',
 '-133.39',
 '-133.38',
 '-133.37',
 '-133.36',
 '-133.35',
 '-133.34',
 '-133.33',
 '-133.32',
 '-133.31',
 '-133.3',
 '-133.29',
 '-133.28',
 '-133.27',
 '-133.26',
 '-133.25',
 '-133.24',
 '-133.23',
 '-133.22',
 '-133.21',
 '-133.2',
 '-133.19',
 '-133.18',
 '-133.17',
 '-133.16',
 '-133.15',
 '-133.14',
 '-133.13',
 '-133.12',
 '-133.11',
 '-133.1',
 '-133.09',
 '-133.08',
 '-133.07',
 '-133.06',
 '-133.05',
 '-133.04',
 '-133.03',
 '-133.02',
 '-133.01',
 '-133.0',
 '-132.99',
 '-132.98',
 '-132.97',
 '-132.96',
 '-132.95',
 '-132.94',
 '-132.93',
 '-132.92',
 '-132.91',
 '-132.9',
 '-132.89',
 '-132.88',
 '-132.87',
 '-132.86',
 '-132.85',
 '-132.84',
 '-132.83',
 '-132.82',
 '-132.81',
 '-132.8',
 '-132.79',
 '-132.78',
 '-132.77',
 '-132.76',
 '-132.75',
 '-132.74',
 '-132.73',
 '-132.72',
 '-132.71',
 '-132.7',
 '-132.69',
 '-132.68',
 '-132.67',
 '-132.66',
 '-132.65',
 '-132.64',
 '-132.63',
 '-132.62',
 '-132.61',
 '-132.6',
 '-132.59',
 '-132.58',
 '-132.57',
 '-132.56',
 '-132.55',
 '-132.54',
 '-132.53',
 '-132.52',
 '-132.51',
 '-132.5',
 '-132.49',
 '-132.48',
 '-132.47',
 '-132.46',
 '-132.45',
 '-132.44',
 '-132.43',
 '-132.42',
 '-132.41',
 '-132.4',
 '-132.39',
 '-132.38',
 '-132.37',
 '-132.36',
 '-132.35',
 '-132.34',
 '-132.33',
 '-132.32',
 '-132.31',
 '-132.3',
 '-132.29',
 '-132.28',
 '-132.27',
 '-132.26',
 '-132.25',
 '-132.24',
 '-132.23',
 '-132.22',
 '-132.21',
 '-132.2',
 '-132.19',
 '-132.18',
 '-132.17',
 '-132.16',
 '-132.15',
 '-132.14',
 '-132.13',
 '-132.12',
 '-132.11',
 '-132.1',
 '-132.09',
 '-132.08',
 '-132.07',
 '-132.06',
 '-132.05',
 '-132.04',
 '-132.03',
 '-132.02',
 '-132.01',
 '-132.0',
 '-131.99',
 '-131.98',
 '-131.97',
 '-131.96',
 '-131.95',
 '-131.94',
 '-131.93',
 '-131.92',
 '-131.91',
 '-131.9',
 '-131.89',
 '-131.88',
 '-131.87',
 '-131.86',
 '-131.85',
 '-131.84',
 '-131.83',
 '-131.82',
 '-131.81',
 '-131.8',
 '-131.79',
 '-131.78',
 '-131.77',
 '-131.76',
 '-131.75',
 '-131.74',
 '-131.73',
 '-131.72',
 '-131.71',
 '-131.7',
 '-131.69',
 '-131.68',
 '-131.67',
 '-131.66',
 '-131.65',
 '-131.64',
 '-131.63',
 '-131.62',
 '-131.61',
 '-131.6',
 '-131.59',
 '-131.58',
 '-131.57',
 '-131.56',
 '-131.55',
 '-131.54',
 '-131.53',
 '-131.52',
 '-131.51',
 '-131.5',
 '-131.49',
 '-131.48',
 '-131.47',
 '-131.46',
 '-131.45',
 '-131.44',
 '-131.43',
 '-131.42',
 '-131.41',
 '-131.4',
 '-131.39',
 '-131.38',
 '-131.37',
 '-131.36',
 '-131.35',
 '-131.34',
 '-131.33',
 '-131.32',
 '-131.31',
 '-131.3',
 '-131.29',
 '-131.28',
 '-131.27',
 '-131.26',
 '-131.25',
 '-131.24',
 '-131.23',
 '-131.22',
 '-131.21',
 '-131.2',
 '-131.19',
 '-131.18',
 '-131.17',
 '-131.16',
 '-131.15',
 '-131.14',
 '-131.13',
 '-131.12',
 '-131.11',
 '-131.1',
 '-131.09',
 '-131.08',
 '-131.07',
 '-131.06',
 '-131.05',
 '-131.04',
 '-131.03',
 '-131.02',
 '-131.01',
 '-131.0',
 '-130.99',
 '-130.98',
 '-130.97',
 '-130.96',
 '-130.95',
 '-130.94',
 '-130.93',
 '-130.92',
 '-130.91',
 '-130.9',
 '-130.89',
 '-130.88',
 '-130.87',
 '-130.86',
 '-130.85',
 '-130.84',
 '-130.83',
 '-130.82',
 '-130.81',
 '-130.8',
 '-130.79',
 '-130.78',
 '-130.77',
 '-130.76',
 '-130.75',
 '-130.74',
 '-130.73',
 '-130.72',
 '-130.71',
 '-130.7',
 '-130.69',
 '-130.68',
 '-130.67',
 '-130.66',
 '-130.65',
 '-130.64',
 '-130.63',
 '-130.62',
 '-130.61',
 '-130.6',
 '-130.59',
 '-130.58',
 '-130.57',
 '-130.56',
 '-130.55',
 '-130.54',
 '-130.53',
 '-130.52',
 '-130.51',
 '-130.5',
 '-130.49',
 '-130.48',
 '-130.47',
 '-130.46',
 '-130.45',
 '-130.44',
 '-130.43',
 '-130.42',
 '-130.41',
 '-130.4',
 '-130.39',
 '-130.38',
 '-130.37',
 '-130.36',
 '-130.35',
 '-130.34',
 '-130.33',
 '-130.32',
 '-130.31',
 '-130.3',
 '-130.29',
 '-130.28',
 '-130.27',
 '-130.26',
 '-130.25',
 '-130.24',
 '-130.23',
 '-130.22',
 '-130.21',
 '-130.2',
 '-130.19',
 '-130.18',
 '-130.17',
 '-130.16',
 '-130.15',
 '-130.14',
 '-130.13',
 '-130.12',
 '-130.11',
 '-130.1',
 '-130.09',
 '-130.08',
 '-130.07',
 '-130.06',
 '-130.05',
 '-130.04',
 '-130.03',
 '-130.02',
 '-130.01',
 '-130.0',
 '-129.99',
 '-129.98',
 '-129.97',
 '-129.96',
 '-129.95',
 '-129.94',
 '-129.93',
 '-129.92',
 '-129.91',
 '-129.9',
 '-129.89',
 '-129.88',
 '-129.87',
 '-129.86',
 '-129.85',
 '-129.84',
 '-129.83',
 '-129.82',
 '-129.81',
 '-129.8',
 '-129.79',
 '-129.78',
 '-129.77',
 '-129.76',
 '-129.75',
 '-129.74',
 '-129.73',
 '-129.72',
 '-129.71',
 '-129.7',
 '-129.69',
 '-129.68',
 '-129.67',
 '-129.66',
 '-129.65',
 '-129.64',
 '-129.63',
 '-129.62',
 '-129.61',
 '-129.6',
 '-129.59',
 '-129.58',
 '-129.57',
 '-129.56',
 '-129.55',
 '-129.54',
 '-129.53',
 '-129.52',
 '-129.51',
 '-129.5',
 '-129.49',
 '-129.48',
 '-129.47',
 '-129.46',
 '-129.45',
 '-129.44',
 '-129.43',
 '-129.42',
 '-129.41',
 '-129.4',
 '-129.39',
 '-129.38',
 '-129.37',
 '-129.36',
 '-129.35',
 '-129.34',
 '-129.33',
 '-129.32',
 '-129.31',
 '-129.3',
 '-129.29',
 '-129.28',
 '-129.27',
 '-129.26',
 '-129.25',
 '-129.24',
 '-129.23',
 '-129.22',
 '-129.21',
 '-129.2',
 '-129.19',
 '-129.18',
 '-129.17',
 '-129.16',
 '-129.15',
 '-129.14',
 '-129.13',
 '-129.12',
 '-129.11',
 '-129.1',
 '-129.09',
 '-129.08',
 '-129.07',
 '-129.06',
 '-129.05',
 '-129.04',
 '-129.03',
 '-129.02',
 '-129.01',
 '-129.0',
 '-128.99',
 '-128.98',
 '-128.97',
 '-128.96',
 '-128.95',
 '-128.94',
 '-128.93',
 '-128.92',
 '-128.91',
 '-128.9',
 '-128.89',
 '-128.88',
 '-128.87',
 '-128.86',
 '-128.85',
 '-128.84',
 '-128.83',
 '-128.82',
 '-128.81',
 '-128.8',
 '-128.79',
 '-128.78',
 '-128.77',
 '-128.76',
 '-128.75',
 '-128.74',
 '-128.73',
 '-128.72',
 '-128.71',
 '-128.7',
 '-128.69',
 '-128.68',
 '-128.67',
 '-128.66',
 '-128.65',
 '-128.64',
 '-128.63',
 '-128.62',
 '-128.61',
 '-128.6',
 '-128.59',
 '-128.58',
 '-128.57',
 '-128.56',
 '-128.55',
 '-128.54',
 '-128.53',
 '-128.52',
 '-128.51',
 '-128.5',
 '-128.49',
 '-128.48',
 '-128.47',
 '-128.46',
 '-128.45',
 '-128.44',
 '-128.43',
 '-128.42',
 '-128.41',
 '-128.4',
 '-128.39',
 '-128.38',
 '-128.37',
 '-128.36',
 '-128.35',
 '-128.34',
 '-128.33',
 '-128.32',
 '-128.31',
 '-128.3',
 '-128.29',
 '-128.28',
 '-128.27',
 '-128.26',
 '-128.25',
 '-128.24',
 '-128.23',
 '-128.22',
 '-128.21',
 '-128.2',
 '-128.19',
 '-128.18',
 '-128.17',
 '-128.16',
 '-128.15',
 '-128.14',
 '-128.13',
 '-128.12',
 '-128.11',
 '-128.1',
 '-128.09',
 '-128.08',
 '-128.07',
 '-128.06',
 '-128.05',
 '-128.04',
 '-128.03',
 '-128.02',
 '-128.01',
 '-128.0',
 ...]

In [19]:
max(lang)

'-99.99'

In [17]:
p1=lang.index(t1)
p2=lati.index(t2)
print(PM2000.iloc[p1,p2])

ValueError: -122.4 is not in list

In [27]:
PM2000.iloc(10.61,56.30)

TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given